include("../conan_parse_arguments.cmake")

set(cmd_name "conan")
set(cmd_args "install")
_arg_get_command_output(_conan_stdout "${cmd_name}" "${cmd_args}")
_arg_output_split(USE POS OPT "${_conan_stdout}" "${cmd_name}" "${cmd_args}")
message("output:")
foreach (line IN LISTS USE)
    message("USE: '${line}'")
endforeach()
message("")
foreach (line IN LISTS OPT)
    message("OPT: '${line}'")
endforeach()
message("")
foreach (line IN LISTS POS)
    message("POS: '${line}'")
endforeach()
message("")

_arg_optional_parse(RES "${OPT}")

list(LENGTH RES_NAME _len)
if (${_len} GREATER 0)
    math(EXPR _len "${_len}-1")
    foreach (_idx RANGE 0 ${_len})
        list(GET RES_NAME ${_idx} _name)
        list(GET RES_LONG ${_idx} _long)
        list(GET RES_SHORT ${_idx} _short)
        list(GET RES_USAGE ${_idx} _usage)
        message("OPT ${_idx}: '${_name}' long: '${_long}' short: '${_short}' usage: '${_usage}'")
    endforeach()
endif()

